# Herramientas para álgebral lineal

¿Preparades para aprender sobre el amplio conjunto de herramientas para álgebra lineal en NumPy? En esta sesión, veremos las funciones especializadas de NumPy para álgebra lineal, fundamentales en áreas como la ciencia de datos y la ingeniería. Veremos desde la descomposición de valores singulares hasta el cálculo de autovalores y autovectores, y veremos cómo NumPy facilita la resolución de problemas complejos en esta área.


In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


In [7]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [6]:
A = np.arange(1,5).reshape(2,-1)
B = np.arange(5,9).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [8]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [9]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [10]:
A@B

array([[19, 22],
       [43, 50]])

In [11]:
A.T

array([[1, 3],
       [2, 4]])

In [12]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [13]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [14]:
np.linalg.det(A)

-2.0000000000000004

In [15]:
b = np.array([9,8])
x = np.linalg.solve(A,b)
x

array([-10. ,   9.5])

In [17]:
eigenvalores, eigenvectores = np.linalg.eig(A)
print(eigenvalores, eigenvectores)

[-0.37228132  5.37228132] [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [18]:
U, S, V = np.linalg.svd(A)
print(U,S,V)

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]] [5.4649857  0.36596619] [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
