# Introducción a NumPy y arrays

¿Listes para explorar NumPy? La biblioteca esencial de Python que ha revolucionado el análisis y la manipulación de datos numéricos. 

Desde la creación de arrays hasta la optimización de operaciones numéricas, exploraremos cada rincón de NumPy. Te guiaremos desde los fundamentos, como la definición de arrays, hasta las técnicas avanzadas que te permitirán realizar operaciones matemáticas y estadísticas con una eficiencia sin precedentes.

A medida que nos sumergimos en las profundidades de NumPy, descubrirás cómo los arrays y las herramientas avanzadas pueden potenciar tu análisis de datos, llevándolo a un nivel más alto. Configura tu entorno Python y acompáñanos en este viaje hacia el dominio total de NumPy, donde cada función y método abre un nuevo camino hacia el conocimiento en la ciencia de datos.

In [1]:
import numpy as np

In [2]:
pip install numpy


[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [ ]:
pip install numpy --upgrade

In [3]:
np.__version__

'1.24.2'

[numpy.org](https://numpy.org)

In [7]:
a1 = np.array([1])

In [8]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([2])

In [10]:
a1+a2

array([3])

In [11]:
a1*a2

array([2])

In [13]:
a2**a1

array([2])

In [15]:
a3 = np.array([1,2,3])
a3

array([1, 2, 3])

In [19]:
a4 = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
a4

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
lista = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
np.array(lista)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
lista = [[1,2,3],[4,5,6],[7,8,9]] # 3 listas en una lista
np.array(lista)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])